// Generated by Bisonc++ V2.09.03 on Sat, 22 Mar 2014 15:17:51 +0530

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {284, 2}, // 1: program ->  optional_declaration_list procedure_definition
     {285, 0}, // 2: optional_declaration_list ->  <empty>
     {285, 1}, // 3: optional_declaration_list ->  variable_declaration_list
     {286, 9}, // 4: procedure_definition (NAME) ->  NAME '(' ')' #0001 '{' optional_variable_declaration_list #0002 basic_block_list '}'
     {287, 0}, // 5: #0001 ->  <empty>
     {288, 0}, // 6: #0002 ->  <empty>
     {289, 0}, // 7: optional_variable_declaration_list ->  <empty>
     {289, 1}, // 8: optional_variable_declaration_list ->  variable_declaration_list
     {290, 1}, // 9: variable_declaration_list ->  variable_declaration
     {290, 2}, // 10: variable_declaration_list ->  variable_declaration_list variable_declaration
     {291, 2}, // 11: variable_declaration (';') ->  declaration ';'
     {292, 2}, // 12: declaration (INTEGER) ->  INTEGER NAME
     {293, 2}, // 13: basic_block_list ->  basic_block_list basic_block
     {293, 1}, // 14: basic_block_list ->  basic_block
     {294, 3}, // 15: basic_block (BBNUM) ->  BBNUM ':' executable_statement_list
     {295, 1}, // 16: executable_statement_list ->  assignment_statement_list
     {295, 3}, // 17: executable_statement_list (RETURN) ->  assignment_statement_list RETURN ';'
     {296, 0}, // 18: assignment_statement_list ->  <empty>
     {296, 2}, // 19: assignment_statement_list ->  assignment_statement_list assignment_statement
     {297, 11}, // 20: assignment_statement (IF) ->  IF '(' comp_stmt ')' GOTO BBNUM ';' ELSE GOTO BBNUM ';'
     {297, 3}, // 21: assignment_statement (GOTO) ->  GOTO BBNUM ';'
     {297, 4}, // 22: assignment_statement (ASSIGN) ->  variable ASSIGN comp_stmt ';'
     {298, 3}, // 23: comp_stmt (GT) ->  comp_stmt GT comp_stmt
     {298, 3}, // 24: comp_stmt (LT) ->  comp_stmt LT comp_stmt
     {298, 3}, // 25: comp_stmt (NE) ->  comp_stmt NE comp_stmt
     {298, 3}, // 26: comp_stmt (GE) ->  comp_stmt GE comp_stmt
     {298, 3}, // 27: comp_stmt (LE) ->  comp_stmt LE comp_stmt
     {298, 3}, // 28: comp_stmt (EQ) ->  comp_stmt EQ comp_stmt
     {298, 3}, // 29: comp_stmt ('(') ->  '(' comp_stmt ')'
     {298, 1}, // 30: comp_stmt ->  variable
     {298, 1}, // 31: comp_stmt ->  constant
     {299, 1}, // 32: variable (NAME) ->  NAME
     {300, 1}, // 33: constant (INTEGER_NUMBER) ->  INTEGER_NUMBER
     {301, 1}, // 34: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_DEF}, {  7} },                             
    { {     284}, {  1} }, // program                  
    { {     285}, {  2} }, // optional_declaration_list
    { {     290}, {  3} }, // variable_declaration_list
    { {     291}, {  4} }, // variable_declaration     
    { {     292}, {  5} }, // declaration              
    { {     261}, {  6} }, // INTEGER                  
    { {       0}, { -2} },                             
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, { 3} },                        
    { {       286}, { 7} }, // procedure_definition
    { {       259}, { 8} }, // NAME                
    { {         0}, { 0} },                        
};

SR__ s_3[] =
{
    { { REQ_DEF}, {  4} },                        
    { {     291}, {  9} }, // variable_declaration
    { {     292}, {  5} }, // declaration         
    { {     261}, {  6} }, // INTEGER             
    { {       0}, { -3} },                        
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 10} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       259}, { 11} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_7[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 12} }, // '('
    { {         0}, {  0} },       
};

SR__ s_9[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_10[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_11[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 13} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_13[] =
{
    { { DEF_RED}, {  2} },         
    { {     287}, { 14} }, // #0001
    { {       0}, { -5} },         
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       123}, { 15} }, // '{'
    { {         0}, {  0} },       
};

SR__ s_15[] =
{
    { { REQ_DEF}, {  6} },                                      
    { {     289}, { 16} }, // optional_variable_declaration_list
    { {     290}, { 17} }, // variable_declaration_list         
    { {     291}, {  4} }, // variable_declaration              
    { {     292}, {  5} }, // declaration                       
    { {     261}, {  6} }, // INTEGER                           
    { {       0}, { -7} },                                      
};

SR__ s_16[] =
{
    { { DEF_RED}, {  2} },         
    { {     288}, { 18} }, // #0002
    { {       0}, { -6} },         
};

SR__ s_17[] =
{
    { { REQ_DEF}, {  4} },                        
    { {     291}, {  9} }, // variable_declaration
    { {     292}, {  5} }, // declaration         
    { {     261}, {  6} }, // INTEGER             
    { {       0}, { -8} },                        
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       293}, { 19} }, // basic_block_list
    { {       294}, { 20} }, // basic_block     
    { {       258}, { 21} }, // BBNUM           
    { {         0}, {  0} },                    
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 22} }, // '}'        
    { {       294}, { 23} }, // basic_block
    { {       258}, { 21} }, // BBNUM      
    { {         0}, {  0} },               
};

SR__ s_20[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        58}, { 24} }, // ':'
    { {         0}, {  0} },       
};

SR__ s_22[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_24[] =
{
    { { DEF_RED}, {   3} },                             
    { {     295}, {  25} }, // executable_statement_list
    { {     296}, {  26} }, // assignment_statement_list
    { {       0}, { -18} },                             
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_26[] =
{
    { { REQ_DEF}, {   7} },                        
    { {     260}, {  27} }, // RETURN              
    { {     297}, {  28} }, // assignment_statement
    { {     262}, {  29} }, // IF                  
    { {     264}, {  30} }, // GOTO                
    { {     299}, {  31} }, // variable            
    { {     259}, {  32} }, // NAME                
    { {       0}, { -16} },                        
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 33} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_28[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 34} }, // '('
    { {         0}, {  0} },       
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       258}, { 35} }, // BBNUM
    { {         0}, {  0} },         
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       265}, { 36} }, // ASSIGN
    { {         0}, {  0} },          
};

SR__ s_32[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, {  7} },                  
    { {       298}, { 37} }, // comp_stmt     
    { {        40}, { 38} }, // '('           
    { {       299}, { 39} }, // variable      
    { {       300}, { 40} }, // constant      
    { {       259}, { 32} }, // NAME          
    { {       257}, { 41} }, // INTEGER_NUMBER
    { {         0}, {  0} },                  
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 42} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, {  7} },                  
    { {       298}, { 43} }, // comp_stmt     
    { {        40}, { 38} }, // '('           
    { {       299}, { 39} }, // variable      
    { {       300}, { 40} }, // constant      
    { {       259}, { 32} }, // NAME          
    { {       257}, { 41} }, // INTEGER_NUMBER
    { {         0}, {  0} },                  
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  8} },       
    { {        41}, { 44} }, // ')'
    { {       270}, { 45} }, // GT 
    { {       268}, { 46} }, // LT 
    { {       266}, { 47} }, // NE 
    { {       271}, { 48} }, // GE 
    { {       269}, { 49} }, // LE 
    { {       267}, { 50} }, // EQ 
    { {         0}, {  0} },       
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  7} },                  
    { {       298}, { 51} }, // comp_stmt     
    { {        40}, { 38} }, // '('           
    { {       299}, { 39} }, // variable      
    { {       300}, { 40} }, // constant      
    { {       259}, { 32} }, // NAME          
    { {       257}, { 41} }, // INTEGER_NUMBER
    { {         0}, {  0} },                  
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  8} },       
    { {        59}, { 52} }, // ';'
    { {       270}, { 45} }, // GT 
    { {       268}, { 46} }, // LT 
    { {       266}, { 47} }, // NE 
    { {       271}, { 48} }, // GE 
    { {       269}, { 49} }, // LE 
    { {       267}, { 50} }, // EQ 
    { {         0}, {  0} },       
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       264}, { 53} }, // GOTO
    { {         0}, {  0} },        
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  7} },                  
    { {       298}, { 54} }, // comp_stmt     
    { {        40}, { 38} }, // '('           
    { {       299}, { 39} }, // variable      
    { {       300}, { 40} }, // constant      
    { {       259}, { 32} }, // NAME          
    { {       257}, { 41} }, // INTEGER_NUMBER
    { {         0}, {  0} },                  
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, {  7} },                  
    { {       298}, { 55} }, // comp_stmt     
    { {        40}, { 38} }, // '('           
    { {       299}, { 39} }, // variable      
    { {       300}, { 40} }, // constant      
    { {       259}, { 32} }, // NAME          
    { {       257}, { 41} }, // INTEGER_NUMBER
    { {         0}, {  0} },                  
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  7} },                  
    { {       298}, { 56} }, // comp_stmt     
    { {        40}, { 38} }, // '('           
    { {       299}, { 39} }, // variable      
    { {       300}, { 40} }, // constant      
    { {       259}, { 32} }, // NAME          
    { {       257}, { 41} }, // INTEGER_NUMBER
    { {         0}, {  0} },                  
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  7} },                  
    { {       298}, { 57} }, // comp_stmt     
    { {        40}, { 38} }, // '('           
    { {       299}, { 39} }, // variable      
    { {       300}, { 40} }, // constant      
    { {       259}, { 32} }, // NAME          
    { {       257}, { 41} }, // INTEGER_NUMBER
    { {         0}, {  0} },                  
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  7} },                  
    { {       298}, { 58} }, // comp_stmt     
    { {        40}, { 38} }, // '('           
    { {       299}, { 39} }, // variable      
    { {       300}, { 40} }, // constant      
    { {       259}, { 32} }, // NAME          
    { {       257}, { 41} }, // INTEGER_NUMBER
    { {         0}, {  0} },                  
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, {  7} },                  
    { {       298}, { 59} }, // comp_stmt     
    { {        40}, { 38} }, // '('           
    { {       299}, { 39} }, // variable      
    { {       300}, { 40} }, // constant      
    { {       259}, { 32} }, // NAME          
    { {       257}, { 41} }, // INTEGER_NUMBER
    { {         0}, {  0} },                  
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {  8} },       
    { {        41}, { 60} }, // ')'
    { {       270}, { 45} }, // GT 
    { {       268}, { 46} }, // LT 
    { {       266}, { 47} }, // NE 
    { {       271}, { 48} }, // GE 
    { {       269}, { 49} }, // LE 
    { {       267}, { 50} }, // EQ 
    { {         0}, {  0} },       
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       258}, { 61} }, // BBNUM
    { {         0}, {  0} },         
};

SR__ s_54[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_55[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_56[] =
{
    { { REQ_DEF}, {   5} },      
    { {     270}, {  45} }, // GT
    { {     268}, {  46} }, // LT
    { {     271}, {  48} }, // GE
    { {     269}, {  49} }, // LE
    { {       0}, { -25} },      
};

SR__ s_57[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_58[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_59[] =
{
    { { REQ_DEF}, {   5} },      
    { {     270}, {  45} }, // GT
    { {     268}, {  46} }, // LT
    { {     271}, {  48} }, // GE
    { {     269}, {  49} }, // LE
    { {       0}, { -28} },      
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 62} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       263}, { 63} }, // ELSE
    { {         0}, {  0} },        
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       264}, { 64} }, // GOTO
    { {         0}, {  0} },        
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       258}, { 65} }, // BBNUM
    { {         0}, {  0} },         
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 66} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_66[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         program_object.set_procedure_map(current_procedure, get_line_number());
         program_object.global_list_in_proc_map_check();
         }
         }
        break;

        case 2:
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * global_table = new Symbol_Table();
         program_object.set_global_table(*global_table);
         }
         }
        break;

        case 3:
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * global_table = d_vsp__[0].symbol_table;
         CHECK_INVARIANT((global_table != NULL), "Global declarations cannot be null");
         program_object.set_global_table(*global_table);
         }
         }
        break;

        case 4:
        {
         if (NOT_ONLY_PARSE)
         {
         list<Basic_Block *> * bb_list = d_vsp__[-1].basic_block_list;
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         CHECK_INVARIANT((bb_list != NULL), "Basic block list cannot be null");
         current_procedure->set_basic_block_list(*bb_list);
         }
         }
        break;

        case 5:
        d_val__ = d_vsp__[-2];
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[-2].string_value != NULL), "Procedure name cannot be null");
         string proc_name = *d_vsp__[-2].string_value;
         current_procedure = new Procedure(void_data_type, proc_name, get_line_number());
         }
         }
        break;

        case 6:
        d_val__ = d_vsp__[-5];
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         Symbol_Table * local_table = d_vsp__[0].symbol_table;
         if (local_table == NULL)
         local_table = new Symbol_Table();
         current_procedure->set_local_list(*local_table);
         }
         }
        break;

        case 7:
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.symbol_table = NULL;
         }
         }
        break;

        case 8:
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[0].symbol_table != NULL), "Declaration statement list cannot be null here");
         d_val__.symbol_table = d_vsp__[0].symbol_table;
         }
         }
        break;

        case 9:
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table_Entry * decl_stmt = d_vsp__[0].symbol_entry;
         CHECK_INVARIANT((decl_stmt != NULL), "Non-terminal declaration statement cannot be null");
         string decl_name = decl_stmt->get_variable_name();
         CHECK_INPUT ((program_object.variable_in_proc_map_check(decl_name) == false),
         "Variable name cannot be same as the procedure name", get_line_number());
         if (current_procedure != NULL)
         {
         CHECK_INPUT((current_procedure->get_proc_name() != decl_name),
         "Variable name cannot be same as procedure name", get_line_number());
         }
         Symbol_Table * decl_list = new Symbol_Table();
         decl_list->push_symbol(decl_stmt);
         d_val__.symbol_table = decl_list;
         }
         }
        break;

        case 10:
        {
         if (NOT_ONLY_PARSE)
         {
         
         
         Symbol_Table_Entry * decl_stmt = d_vsp__[0].symbol_entry;
         Symbol_Table * decl_list = d_vsp__[-1].symbol_table;
         CHECK_INVARIANT((decl_stmt != NULL), "The declaration statement cannot be null");
         CHECK_INVARIANT((decl_list != NULL), "The declaration statement list cannot be null");
         string decl_name = decl_stmt->get_variable_name();
         CHECK_INPUT((program_object.variable_in_proc_map_check(decl_name) == false),
         "Procedure name cannot be same as the variable name", get_line_number());
         if (current_procedure != NULL)
         {
         CHECK_INPUT((current_procedure->get_proc_name() != decl_name),
         "Variable name cannot be same as procedure name", get_line_number());
         }
         CHECK_INPUT((decl_list->variable_in_symbol_list_check(decl_name) == false), 
         "Variable is declared twice", get_line_number());
         decl_list->push_symbol(decl_stmt);
         d_val__.symbol_table = decl_list;
         }
         }
        break;

        case 11:
        {
         if (NOT_ONLY_PARSE)
         {
         pair<Data_Type, string> * decl_stmt = d_vsp__[-1].decl;
         CHECK_INVARIANT((decl_stmt != NULL), "Declaration cannot be null");
         Data_Type type = decl_stmt->first;
         string decl_name = decl_stmt->second;
         Symbol_Table_Entry * decl_entry = new Symbol_Table_Entry(decl_name, type, get_line_number());
         d_val__.symbol_entry = decl_entry;
         }
         }
        break;

        case 12:
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[0].string_value != NULL), "Name cannot be null");
         string name = *d_vsp__[0].string_value;
         Data_Type type = int_data_type;
         pair<Data_Type, string> * declar = new pair<Data_Type, string>(type, name);
         d_val__.decl = declar;
         }
         }
        break;

        case 13:
        {
         if (NOT_ONLY_PARSE)
         {
         list<Basic_Block *> * bb_list = d_vsp__[-1].basic_block_list;
         Basic_Block * bb = d_vsp__[0].basic_block;
         CHECK_INVARIANT((bb_list != NULL), "New basic block cannot be null");
         CHECK_INVARIANT((bb != NULL), "Basic block cannot be null");
         bb_strictly_increasing_order_check(bb_list, bb->get_bb_number());
         bb_list->push_back(d_vsp__[0].basic_block);
         d_val__.basic_block_list = bb_list;
         }
         }
        break;

        case 14:
        {
         if (NOT_ONLY_PARSE)
         {
         Basic_Block * bb = d_vsp__[0].basic_block;
         CHECK_INVARIANT((bb != NULL), "Basic block cannot be null");
         list<Basic_Block *> * bb_list = new list<Basic_Block *>;
         bb_list->push_back(bb);
         d_val__.basic_block_list = bb_list;
         }
         }
        break;

        case 15:
        {
         if (NOT_ONLY_PARSE)
         {
         int bb_number = d_vsp__[-2].integer_value;
         list<Ast *> * exe_stmt = d_vsp__[0].ast_list;
         CHECK_INPUT((bb_number >= 2), "Illegal basic block lable", get_line_number());
         Basic_Block * bb = new Basic_Block(bb_number, get_line_number());
         if (exe_stmt != NULL)
         bb->set_ast_list(*exe_stmt);
         else
         {
         list<Ast *> * ast_list = new list<Ast *>;
         bb->set_ast_list(*ast_list);
         }
         d_val__.basic_block = bb;
         }
         }
        break;

        case 16:
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast_list = d_vsp__[0].ast_list;
         }
         }
        break;

        case 17:
        {
         if (NOT_ONLY_PARSE)
         {
         list<Ast *> * assign_list = d_vsp__[-2].ast_list;
         Ast * ret = new Return_Ast(get_line_number());
         list<Ast *> * exe_list = NULL;
         if (assign_list)
         exe_list = assign_list;
         else
         exe_list = new list<Ast *>;
         exe_list->push_back(ret);
         d_val__.ast_list = exe_list;
         }
         }
        break;

        case 18:
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast_list = NULL;
         }
         }
        break;

        case 19:
        {
         if (NOT_ONLY_PARSE)
         {
         list<Ast *> * assign_list = d_vsp__[-1].ast_list;
         Ast * assign_stmt = d_vsp__[0].ast;
         list<Ast *> * assign_list_new = NULL;
         CHECK_INVARIANT((assign_stmt != NULL), "Assignment statement cannot be null");
         if (assign_list == NULL)
         assign_list_new = new list<Ast *>;
         else
         assign_list_new = assign_list;
         assign_list_new->push_back(assign_stmt);
         d_val__.ast_list = assign_list_new;
         }
         }
        break;

        case 20:
        {
         if (NOT_ONLY_PARSE)
         {
         
         d_val__.ast = new If_Else_Ast(d_vsp__[-8].ast,d_vsp__[-5].integer_value,d_vsp__[-1].integer_value);
         int line = get_line_number();
         }
         }
        break;

        case 21:
        {
         if (NOT_ONLY_PARSE)
         { 
         d_val__.ast = new GOTO_AST(d_vsp__[-1].integer_value);
         int line = get_line_number();
         }
         }
        break;

        case 22:
        {
         if (NOT_ONLY_PARSE)
         {
         int line = get_line_number();
         d_val__.ast = new Assignment_Ast(d_vsp__[-3].ast, d_vsp__[-1].ast,line);
         d_val__.ast->check_ast();
         }
         }
        break;

        case 23:
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = new Comparison_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, 1);
         int line = get_line_number();
         d_val__.ast->check_ast();
         }
         }
        break;

        case 24:
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = new Comparison_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, 3);
         int line = get_line_number();
         d_val__.ast->check_ast();
         }
         }
        break;

        case 25:
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = new Comparison_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, 5);
         int line = get_line_number();
         d_val__.ast->check_ast();
         } 
         }
        break;

        case 26:
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = new Comparison_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, 0);
         int line = get_line_number();
         d_val__.ast->check_ast();
         }
         }
        break;

        case 27:
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = new Comparison_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, 2);
         int line = get_line_number();
         d_val__.ast->check_ast();
         }
         }
        break;

        case 28:
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = new Comparison_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, 4);
         int line = get_line_number();
         d_val__.ast->check_ast();
         } 
         }
        break;

        case 29:
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[-1].ast;
         } 
         }
        break;

        case 30:
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 31:
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 32:
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table_Entry * var_table_entry;
         CHECK_INVARIANT((d_vsp__[0].string_value != NULL), "Variable name cannot be null");
         string var_name = *d_vsp__[0].string_value;
         if (current_procedure->variable_in_symbol_list_check(var_name) == true)
         var_table_entry = &(current_procedure->get_symbol_table_entry(var_name));
         else if (program_object.variable_in_symbol_list_check(var_name) == true)
         var_table_entry = &(program_object.get_symbol_table_entry(var_name));
         else
         CHECK_INVARIANT(CONTROL_SHOULD_NOT_REACH, "Variable has not been declared");
         Ast * name_ast = new Name_Ast(var_name, *var_table_entry, get_line_number());
         d_val__.ast = name_ast;
         }
         }
        break;

        case 33:
        {
         if (NOT_ONLY_PARSE)
         {
         int num = d_vsp__[0].integer_value;
         Ast * num_ast = new Number_Ast<int>(num, int_data_type, get_line_number());
         d_val__.ast = num_ast;
         }
         }
        break;

    }
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}

